#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Nozaki
#SPDX-License-Identifier: BSD-3-Clause 
import sys

def tonum(s):
    try:
       return int(s)
    except:
       return float(s)
ans=0
z =0
for line in sys.stdin:
    line = line.rstrip()
    ans+=tonum(line)

print(ans)

if ans <= 1:
    z = 0
else:
    for i in range(2, int(ans**0.5)+1):
        if ans % i == 0:
            z = 1
            print("素数じゃない")
            break
        else:
            z = 0
            break

if z==0:
   print("素数ゥ")
